<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require APP_ROOT . '/includes/admin-layout.php';
$admin = require_admin('editor');
$pdo = db();
$pages = $pdo->query("SELECT p.*, COALESCE(ar.title,en.title,p.slug) title FROM pages p LEFT JOIN page_translations ar ON ar.page_id=p.id AND ar.locale='ar' LEFT JOIN page_translations en ON en.page_id=p.id AND en.locale='en' ORDER BY p.updated_at DESC")->fetchAll();
$media = $pdo->query('SELECT * FROM media_library ORDER BY created_at DESC LIMIT 12')->fetchAll();
$pageId = (int) ($_GET['id'] ?? 0);
$page = null; $translations = ['ar'=>[],'en'=>[]]; $blocks = [];
if ($pageId > 0) {
    $statement=$pdo->prepare('SELECT * FROM pages WHERE id=:id');$statement->execute(['id'=>$pageId]);$page=$statement->fetch()?:null;
    if ($page) {
        $statement=$pdo->prepare('SELECT * FROM page_translations WHERE page_id=:id');$statement->execute(['id'=>$pageId]);foreach($statement->fetchAll() as $row)$translations[$row['locale']]=$row;
        $statement=$pdo->prepare('SELECT * FROM content_blocks WHERE page_id=:id ORDER BY sort_order,id');$statement->execute(['id'=>$pageId]);$blocks=$statement->fetchAll();
        $blockTranslation=$pdo->prepare('SELECT locale,content_json FROM content_block_translations WHERE block_id=:id');
        foreach($blocks as &$block){$block['translations']=['ar'=>[],'en'=>[]];$blockTranslation->execute(['id'=>$block['id']]);foreach($blockTranslation->fetchAll() as $row)$block['translations'][$row['locale']]=cms_decode_json($row['content_json']);}
    }
}
render_admin_start($admin, 'الصفحات والمحتوى', 'content');
?>
<div class="admin-heading"><div><span>BILINGUAL CONTENT SYSTEM</span><h1><?= $page ? 'تحرير الصفحة' : 'الصفحات والمقالات' ?></h1><p>أنشئ صفحة أو مقالاً، ثم كوّنها من الفقرات والصور والمعارض والعناصر التفاعلية.</p></div><?php if($page): ?><a class="admin-primary" target="_blank" href="<?= h(site_url('page.php?slug='.$page['slug'].'&lang=ar')) ?>">معاينة الصفحة ↗</a><?php endif; ?></div>
<div class="admin-grid">
  <aside class="admin-card narrow"><div class="card-title"><div><span>CONTENT TREE</span><h2>كل الصفحات</h2></div><a class="admin-secondary" href="<?= h(admin_url('content.php')) ?>">＋ جديد</a></div><div class="page-list"><?php if(!$pages): ?><p style="font-size:.72rem;color:#7a6870">لا توجد صفحات بعد.</p><?php endif; ?><?php foreach($pages as $item): ?><a class="<?= $pageId===(int)$item['id']?'active':'' ?>" href="<?= h(admin_url('content.php?id='.$item['id'])) ?>"><strong><?= h($item['title']) ?><span>/<?= h($item['slug']) ?></span></strong><span><?= h($item['status']) ?><?= $item['is_blog']?' · مقال':'' ?></span></a><?php endforeach; ?></div><div class="card-title" style="margin-top:28px"><div><span>MEDIA LIBRARY</span><h2>رفع صور المحتوى</h2></div><em>حتى 12</em></div><form class="admin-form" method="post" enctype="multipart/form-data" action="<?= h(admin_url('api.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="upload_cms_media"><input type="hidden" name="fallback" value="content.php<?= $page?'?id='.$pageId:'' ?>"><input type="hidden" name="page_id" value="<?= $pageId ?>"><label class="admin-field full"><span>صور JPG / PNG / WebP / GIF</span><input name="media_files[]" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple required></label><label class="admin-field full"><span>عنوان المجموعة</span><input name="media_title"></label><div class="admin-form-actions"><button class="admin-primary" type="submit">رفع إلى المكتبة</button></div></form><?php if($media): ?><div class="page-list" style="margin-top:16px"><?php foreach($media as $asset): ?><a title="انسخ المسار"><strong><?= h($asset['title']?:$asset['original_name']) ?><span dir="ltr"><?= h($asset['file_path']) ?></span></strong><span><?= (int)$asset['width'] ?>×<?= (int)$asset['height'] ?></span></a><?php endforeach; ?></div><?php endif; ?></aside>
  <section class="admin-card wide"><div class="card-title"><div><span>PAGE DETAILS</span><h2><?= $page?'معلومات الصفحة':'إنشاء صفحة جديدة' ?></h2></div><em>AR + EN</em></div>
    <form class="admin-form" method="post" action="<?= h(admin_url('api.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="save_page"><input type="hidden" name="fallback" value="content.php<?= $page?'?id='.$pageId:'' ?>"><input type="hidden" name="page_id" value="<?= $pageId ?>">
      <label class="admin-field"><span>العنوان العربي</span><input name="title_ar" value="<?= h($translations['ar']['title']??'') ?>" required></label><label class="admin-field"><span>English title</span><input name="title_en" value="<?= h($translations['en']['title']??'') ?>" dir="ltr" required></label>
      <label class="admin-field full"><span>الرابط المختصر — أحرف وأرقام وشرطات</span><input name="slug" value="<?= h($page['slug']??'') ?>" pattern="[A-Za-z0-9\x{0600}-\x{06FF}-]+" dir="ltr" required></label>
      <label class="admin-field"><span>الموجز العربي</span><textarea name="excerpt_ar" rows="3"><?= h($translations['ar']['excerpt']??'') ?></textarea></label><label class="admin-field"><span>English excerpt</span><textarea name="excerpt_en" rows="3" dir="ltr"><?= h($translations['en']['excerpt']??'') ?></textarea></label>
      <label class="admin-field"><span>عنوان SEO العربي</span><input name="seo_title_ar" value="<?= h($translations['ar']['seo_title']??'') ?>"></label><label class="admin-field"><span>English SEO title</span><input name="seo_title_en" value="<?= h($translations['en']['seo_title']??'') ?>" dir="ltr"></label>
      <label class="admin-field"><span>وصف SEO العربي</span><textarea name="seo_description_ar" rows="2"><?= h($translations['ar']['seo_description']??'') ?></textarea></label><label class="admin-field"><span>English SEO description</span><textarea name="seo_description_en" rows="2" dir="ltr"><?= h($translations['en']['seo_description']??'') ?></textarea></label>
      <label class="admin-field"><span>حالة النشر</span><select name="status"><option value="draft" <?= ($page['status']??'draft')==='draft'?'selected':'' ?>>مسودة</option><option value="published" <?= ($page['status']??'')==='published'?'selected':'' ?>>منشورة</option><option value="archived" <?= ($page['status']??'')==='archived'?'selected':'' ?>>مؤرشفة</option></select></label><label class="admin-field"><span>نمط العرض</span><select name="template"><option value="editorial" <?= ($page['template']??'editorial')==='editorial'?'selected':'' ?>>تحريري</option><option value="clinical" <?= ($page['template']??'')==='clinical'?'selected':'' ?>>طبي واضح</option><option value="cinematic" <?= ($page['template']??'')==='cinematic'?'selected':'' ?>>سينمائي</option></select></label>
      <label class="admin-field full" style="flex-direction:row;align-items:center"><input style="width:auto" type="checkbox" name="is_blog" value="1" <?= !empty($page['is_blog'])?'checked':'' ?>><span>هذه الصفحة مقال ويظهر في قسم المستجدات</span></label>
      <div class="admin-form-actions"><button class="admin-primary" type="submit"><?= $page?'حفظ الصفحة':'إنشاء الصفحة' ?></button><?php if($page): ?><button class="admin-danger" type="submit" name="action" value="archive_page" data-confirm="سيتم إخفاء الصفحة من الموقع. هل تريد المتابعة؟">أرشفة الصفحة</button><?php endif; ?></div>
    </form>
  </section>
</div>
<?php if($page): ?>
<section class="admin-card full" id="blocks" style="margin-top:18px"><div class="card-title"><div><span>PAGE BUILDER</span><h2>مكوّنات الصفحة</h2></div><em><?= count($blocks) ?> عنصر</em></div>
<?php foreach($blocks as $index=>$block):
  $ar=$block['translations']['ar'];$en=$block['translations']['en'];$settings=cms_decode_json($block['settings_json']);$type=$block['block_type'];
  $titleAr=$ar['title']??$ar['author']??$ar['alt']??'';$titleEn=$en['title']??$en['author']??$en['alt']??'';
  $bodyAr=$ar['body']??$ar['quote']??$ar['caption']??'';$bodyEn=$en['body']??$en['quote']??$en['caption']??'';
  $media='';if($type==='image')$media=$ar['src']??'';elseif(in_array($type,['gallery','slideshow'],true))$media=implode("\n",array_column($ar['images']??[],'src'));
  ?>
  <details class="block-card" <?= $index===0?'open':'' ?>><summary><span><?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?> · <?= h($type) ?></span><span><?= h($titleAr?:mb_substr(strip_tags($bodyAr),0,60)) ?></span></summary><form class="admin-form" method="post" action="<?= h(admin_url('api.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="save_block"><input type="hidden" name="fallback" value="content.php?id=<?= $pageId ?>#blocks"><input type="hidden" name="page_id" value="<?= $pageId ?>"><input type="hidden" name="block_id" value="<?= (int)$block['id'] ?>"><input type="hidden" name="block_type" value="<?= h($type) ?>">
  <label class="admin-field"><span>العنوان / الاسم العربي</span><input name="title_ar" value="<?= h($titleAr) ?>"></label><label class="admin-field"><span>English title / name</span><input name="title_en" value="<?= h($titleEn) ?>" dir="ltr"></label>
  <?php if($type==='rich_text'): ?><label class="admin-field"><span>المحتوى المنسق العربي</span><textarea name="rich_ar" rows="8"><?= h($ar['html']??'') ?></textarea></label><label class="admin-field"><span>English rich content</span><textarea name="rich_en" rows="8" dir="ltr"><?= h($en['html']??'') ?></textarea></label>
  <?php elseif($type==='html_element'): ?><label class="admin-field full"><span>HTML داخل صندوق معزول</span><textarea class="code" name="custom_html"><?= h($ar['html']??'') ?></textarea></label><label class="admin-field"><span>CSS</span><textarea class="code" name="custom_css"><?= h($ar['css']??'') ?></textarea></label><label class="admin-field"><span>JavaScript</span><textarea class="code" name="custom_js"><?= h($ar['js']??'') ?></textarea></label>
  <?php elseif($type==='flowchart'): ?><label class="admin-field"><span>العُقد العربية JSON</span><textarea class="code" name="nodes_json_ar"><?= h(json_encode($ar['nodes']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) ?></textarea></label><label class="admin-field"><span>English nodes JSON</span><textarea class="code" name="nodes_json_en"><?= h(json_encode($en['nodes']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) ?></textarea></label><label class="admin-field full"><span>Connections JSON</span><textarea class="code" name="edges_json"><?= h(json_encode($ar['edges']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) ?></textarea></label>
  <?php else: ?><label class="admin-field"><span>النص العربي</span><textarea name="body_ar" rows="5"><?= h($bodyAr) ?></textarea></label><label class="admin-field"><span>English text</span><textarea name="body_en" rows="5" dir="ltr"><?= h($bodyEn) ?></textarea></label><?php endif; ?>
  <?php if(in_array($type,['paragraph','hero','cta'],true)): ?><label class="admin-field"><span>الوسم العربي الصغير</span><input name="eyebrow_ar" value="<?= h($ar['eyebrow']??'') ?>"></label><label class="admin-field"><span>English eyebrow</span><input name="eyebrow_en" value="<?= h($en['eyebrow']??'') ?>" dir="ltr"></label><?php endif; ?>
  <?php if(in_array($type,['image','gallery','slideshow'],true)): ?><label class="admin-field full"><span><?= $type==='image'?'مسار الصورة':'مسار كل صورة في سطر' ?></span><textarea name="media_urls" rows="4" dir="ltr"><?= h($media) ?></textarea></label><?php endif; ?>
  <?php if(in_array($type,['hero','cta'],true)): ?><label class="admin-field"><span>نص الزر العربي</span><input name="button_label_ar" value="<?= h($ar['button_label']??'') ?>"></label><label class="admin-field"><span>English button label</span><input name="button_label_en" value="<?= h($en['button_label']??'') ?>" dir="ltr"></label><label class="admin-field full"><span>رابط الزر</span><input name="button_url" value="<?= h($ar['button_url']??'#') ?>" dir="ltr"></label><?php endif; ?>
  <label class="admin-field"><span>لون القسم</span><select name="tone"><option value="light" <?= ($settings['tone']??'light')==='light'?'selected':'' ?>>أبيض</option><option value="soft" <?= ($settings['tone']??'')==='soft'?'selected':'' ?>>فاتح</option><option value="dark" <?= ($settings['tone']??'')==='dark'?'selected':'' ?>>داكن</option><option value="green" <?= ($settings['tone']??'')==='green'?'selected':'' ?>>أخضر</option></select></label>
  <div class="admin-form-actions"><button class="admin-primary" type="submit">حفظ العنصر</button><button class="admin-secondary" type="submit" name="action" value="move_block" formaction="<?= h(admin_url('api.php?direction=up')) ?>">تحريك للأعلى</button><button class="admin-secondary" type="submit" name="action" value="move_block" formaction="<?= h(admin_url('api.php?direction=down')) ?>">تحريك للأسفل</button><button class="admin-danger" type="submit" name="action" value="delete_block" data-confirm="حذف هذا العنصر نهائياً؟">حذف</button></div></form></details>
<?php endforeach; ?>
<details class="block-card" open><summary><span>＋ إضافة عنصر جديد</span><span>نص، صورة، معرض، مخطط، أو عنصر برمجي</span></summary><form class="admin-form" method="post" action="<?= h(admin_url('api.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="save_block"><input type="hidden" name="fallback" value="content.php?id=<?= $pageId ?>#blocks"><input type="hidden" name="page_id" value="<?= $pageId ?>"><label class="admin-field full"><span>نوع العنصر</span><select name="block_type" data-block-type><option value="paragraph">فقرة وعنوان</option><option value="rich_text">نص منسق</option><option value="hero">واجهة رئيسية</option><option value="quote">اقتباس</option><option value="image">صورة</option><option value="gallery">معرض صور</option><option value="slideshow">سلايد شو</option><option value="flowchart">مخطط عقد وروابط</option><?php if(admin_can($admin,'super_admin')):?><option value="html_element">HTML / CSS / JS معزول</option><?php endif; ?><option value="cta">دعوة لاتخاذ إجراء</option></select></label>
<label class="admin-field"><span>العنوان العربي</span><input name="title_ar"></label><label class="admin-field"><span>English title</span><input name="title_en" dir="ltr"></label><label class="admin-field"><span>النص العربي</span><textarea name="body_ar" rows="5"></textarea></label><label class="admin-field"><span>English text</span><textarea name="body_en" rows="5" dir="ltr"></textarea></label>
<label class="admin-field" data-for-types="paragraph,hero,cta"><span>الوسم العربي الصغير</span><input name="eyebrow_ar"></label><label class="admin-field" data-for-types="paragraph,hero,cta"><span>English eyebrow</span><input name="eyebrow_en" dir="ltr"></label>
<label class="admin-field full" data-for-types="rich_text"><span>المحتوى المنسق العربي HTML آمن</span><textarea name="rich_ar" rows="6"></textarea></label><label class="admin-field full" data-for-types="rich_text"><span>English rich content</span><textarea name="rich_en" rows="6" dir="ltr"></textarea></label>
<label class="admin-field full" data-for-types="image,gallery,slideshow"><span>مسارات الصور — كل صورة في سطر للمعرض</span><textarea name="media_urls" rows="5" dir="ltr"></textarea></label>
<label class="admin-field" data-for-types="flowchart"><span>العُقد العربية JSON</span><textarea class="code" name="nodes_json_ar">[{"id":"a","title":"البداية","text":"الخطوة الأولى","x":20,"y":45}]</textarea></label><label class="admin-field" data-for-types="flowchart"><span>English nodes JSON</span><textarea class="code" name="nodes_json_en">[{"id":"a","title":"Start","text":"First step","x":20,"y":45}]</textarea></label><label class="admin-field full" data-for-types="flowchart"><span>الروابط JSON</span><textarea class="code" name="edges_json">[]</textarea></label>
<label class="admin-field full" data-for-types="html_element"><span>HTML — يعمل داخل iframe معزول</span><textarea class="code" name="custom_html"></textarea></label><label class="admin-field" data-for-types="html_element"><span>CSS</span><textarea class="code" name="custom_css"></textarea></label><label class="admin-field" data-for-types="html_element"><span>JavaScript</span><textarea class="code" name="custom_js"></textarea></label>
<label class="admin-field" data-for-types="hero,cta"><span>نص الزر العربي</span><input name="button_label_ar"></label><label class="admin-field" data-for-types="hero,cta"><span>English button label</span><input name="button_label_en" dir="ltr"></label><label class="admin-field full" data-for-types="hero,cta"><span>رابط الزر</span><input name="button_url" value="#" dir="ltr"></label>
<label class="admin-field"><span>لون القسم</span><select name="tone"><option value="light">أبيض</option><option value="soft">فاتح</option><option value="dark">داكن</option><option value="green">أخضر</option></select></label><div class="admin-form-actions"><button class="admin-primary" type="submit">إضافة العنصر</button></div></form></details>
</section>
<?php endif; ?>
<?php render_admin_end(); ?>
