<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require APP_ROOT . '/includes/admin-layout.php';
$admin = require_admin('reviewer');
$pdo = db();
$conversations = $pdo->query("SELECT c.*,v.full_name,v.email,v.phone,v.company,(SELECT sender_type FROM conversation_messages WHERE conversation_id=c.id ORDER BY created_at DESC,id DESC LIMIT 1) last_sender,(SELECT body FROM conversation_messages WHERE conversation_id=c.id ORDER BY created_at DESC,id DESC LIMIT 1) last_body FROM conversations c JOIN visitors v ON v.id=c.visitor_id ORDER BY CASE c.status WHEN 'open' THEN 0 WHEN 'pending' THEN 1 ELSE 2 END,c.last_message_at DESC LIMIT 100")->fetchAll();
$id = clean_text($_GET['id'] ?? ($conversations[0]['id'] ?? ''), 50);
$selected = null; $messages = [];
if ($id !== '') {
    $statement=$pdo->prepare('SELECT c.*,v.full_name,v.email,v.phone,v.company,v.details FROM conversations c JOIN visitors v ON v.id=c.visitor_id WHERE c.id=:id');$statement->execute(['id'=>$id]);$selected=$statement->fetch()?:null;
    if($selected){$statement=$pdo->prepare('SELECT m.*,a.id attachment_id,a.mime_type,a.original_name FROM conversation_messages m LEFT JOIN attachments a ON a.message_id=m.id WHERE m.conversation_id=:id ORDER BY m.created_at,m.id');$statement->execute(['id'=>$id]);$messages=$statement->fetchAll();}
}
render_admin_start($admin, 'المراسلات', 'messages');
?>
<div class="admin-heading"><div><span>SECURE INBOX</span><h1>المراسلات والردود</h1><p>كل محادثة وملف وحجز محفوظ ضمن سجل واحد قابل للمتابعة.</p></div><div><span class="status-pill"><?= count($conversations) ?> محادثة</span></div></div>
<section class="conversation-layout">
  <aside class="conversation-list"><?php if(!$conversations): ?><p style="padding:12px;font-size:.72rem;color:#7a6870">لا توجد محادثات بعد.</p><?php endif; ?><?php foreach($conversations as $conversation): ?><a class="<?= $id===$conversation['id']?'active':'' ?>" href="<?= h(admin_url('conversations.php?id='.$conversation['id'])) ?>"><strong><?= h($conversation['full_name']) ?> <?= $conversation['last_sender']==='visitor'?'●':'' ?></strong><span><?= h(mb_substr((string)$conversation['last_body'],0,70)) ?></span><span dir="ltr"><?= h(substr($conversation['last_message_at'],0,16)) ?> · <?= h($conversation['status']) ?></span></a><?php endforeach; ?></aside>
  <div class="conversation-view">
  <?php if(!$selected): ?><div style="padding:50px;text-align:center;color:#7a6870">اختر محادثة لعرضها.</div><?php else: ?>
    <header class="conversation-head"><div><strong><?= h($selected['full_name']) ?></strong><span style="display:block;font-size:.65rem;color:#7a6870"><?= h($selected['email']) ?> · <?= h($selected['phone']) ?> · <?= h($selected['company']) ?></span></div><form method="post" action="<?= h(admin_url('api.php')) ?>" style="display:flex;gap:8px"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="conversation_status"><input type="hidden" name="fallback" value="conversations.php?id=<?= h($id) ?>"><input type="hidden" name="conversation_id" value="<?= h($id) ?>"><select name="status" style="border:1px solid #e6dce1;border-radius:999px;padding:6px 10px"><option value="open" <?= $selected['status']==='open'?'selected':'' ?>>مفتوحة</option><option value="pending" <?= $selected['status']==='pending'?'selected':'' ?>>بانتظار الزائر</option><option value="closed" <?= $selected['status']==='closed'?'selected':'' ?>>مغلقة</option></select><button class="admin-secondary" type="submit">حفظ</button></form></header>
    <div class="conversation-messages"><?php foreach($messages as $message): ?><article class="admin-message <?= h($message['sender_type']) ?>"><?php if($message['attachment_id']): ?><?php if(str_starts_with((string)$message['mime_type'],'image/')): ?><a href="<?= h(site_url('media.php?id='.$message['attachment_id'])) ?>" target="_blank"><img style="max-width:260px;max-height:220px;border-radius:10px" src="<?= h(site_url('media.php?id='.$message['attachment_id'])) ?>" alt="<?= h($message['original_name']) ?>"></a><?php elseif(str_starts_with((string)$message['mime_type'],'audio/')||str_starts_with((string)$message['mime_type'],'video/')): ?><audio controls preload="metadata" src="<?= h(site_url('media.php?id='.$message['attachment_id'])) ?>"></audio><?php else: ?><a href="<?= h(site_url('media.php?id='.$message['attachment_id'])) ?>"><?= h($message['original_name']) ?> ↗</a><?php endif; ?><?php endif; ?><?php if($message['body']!==''): ?><p><?= nl2br(h($message['body'])) ?></p><?php endif; ?><?php if($message['booking_id']): ?><a href="<?= h(admin_url('calendar.php?booking='.$message['booking_id'])) ?>">فتح الحجز في التقويم ↗</a><?php endif; ?><time><?= h(substr($message['created_at'],0,16)) ?></time></article><?php endforeach; ?></div>
    <form class="reply-form" method="post" enctype="multipart/form-data" action="<?= h(admin_url('api.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="conversation_reply"><input type="hidden" name="fallback" value="conversations.php?id=<?= h($id) ?>"><input type="hidden" name="conversation_id" value="<?= h($id) ?>"><input type="hidden" name="purpose" value="file"><textarea name="body" rows="3" maxlength="4000" placeholder="اكتب رد الفريق…"></textarea><div style="display:flex;flex-direction:column;gap:7px"><input name="attachment" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,.docx,audio/webm,audio/mpeg" style="font-size:.6rem;max-width:170px"><select name="purpose" style="font-size:.65rem"><option value="file">ملف</option><option value="image">صورة</option><option value="audio">صوت</option></select><button class="admin-primary" type="submit">إرسال الرد</button></div></form>
  <?php endif; ?>
  </div>
</section>
<?php render_admin_end(); ?>
