<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require APP_ROOT . '/includes/admin-layout.php';
$admin = require_admin('super_admin');
$backups=[];foreach(glob(BACKUP_PATH.DIRECTORY_SEPARATOR.'*')?:[] as $path)if(is_file($path))$backups[]=['name'=>basename($path),'size'=>filesize($path),'date'=>date('Y-m-d H:i',filemtime($path))];usort($backups,static fn($a,$b)=>strcmp($b['date'],$a['date']));
$updates=db()->query('SELECT * FROM update_history ORDER BY id DESC LIMIT 12')->fetchAll();
render_admin_start($admin, 'النسخ والتحديث', 'maintenance');
?>
<div class="admin-heading"><div><span>MAINTENANCE CENTRE</span><h1>النسخ الاحتياطي والتحديث</h1><p>نسخ ملفات الموقع وقاعدة البيانات، استعادة قاعدة موثوقة، أو تطبيق حزمة تحديث مفحوصة.</p></div><span class="status-pill">الإصدار <?= h(setting('site_version','2.0.0')) ?></span></div>
<div class="admin-grid">
  <section class="admin-card wide"><div class="card-title"><div><span>BACKUPS</span><h2>تنزيل نسخة احتياطية</h2></div><em>تُنشأ لحظة الطلب</em></div><p style="color:#7a6870;font-size:.75rem">نسخة الملفات تستثني البيانات السرية، ونسخة قاعدة البيانات تُنشأ كملف MySQL SQL موقّع من النظام.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="admin-primary" href="<?= h(admin_url('download.php?type=files')) ?>">تنزيل ملفات الاستضافة ZIP</a><a class="admin-secondary" href="<?= h(admin_url('download.php?type=database')) ?>">تنزيل قاعدة البيانات SQL</a></div></section>
  <section class="admin-card narrow"><div class="card-title"><div><span>RECENT</span><h2>آخر النسخ</h2></div><em><?= count($backups) ?></em></div><div class="page-list"><?php foreach(array_slice($backups,0,6) as $backup): ?><a><strong><?= h($backup['name']) ?><span><?= number_format($backup['size']/1048576,2) ?> MB</span></strong><span dir="ltr"><?= h($backup['date']) ?></span></a><?php endforeach; ?></div></section>
  <section class="admin-card wide maintenance-zone"><div class="card-title"><div><span>DATABASE RESTORE</span><h2>استعادة قاعدة البيانات</h2></div><em>إعادة دخول مطلوبة</em></div><h3>عملية حساسة</h3><p style="font-size:.74rem">تقبل الأداة ملف MySQL بصيغة SQL صادر من هذا النظام فقط، وتُنشئ نسخة من القاعدة الحالية قبل الاستعادة.</p><form class="admin-form" method="post" enctype="multipart/form-data" action="<?= h(admin_url('maintenance-action.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="restore_database"><label class="admin-field full"><span>ملف MySQL SQL</span><input name="database" type="file" accept=".sql" required></label><label class="admin-field"><span>كلمة مرورك الحالية</span><input name="password" type="password" required></label><label class="admin-field"><span>اكتب RESTORE للتأكيد</span><input name="confirmation" pattern="RESTORE" required dir="ltr"></label><div class="admin-form-actions"><button class="admin-danger" type="submit" data-confirm="سيتم استبدال بيانات قاعدة البيانات. هل أنت متأكد؟">فحص واستعادة القاعدة</button></div></form></section>
  <section class="admin-card narrow maintenance-zone"><div class="card-title"><div><span>UPDATE ZIP</span><h2>تطبيق تحديث</h2></div><em>update.json مطلوب</em></div><h3>حزم موثوقة فقط</h3><form class="admin-form" method="post" enctype="multipart/form-data" action="<?= h(admin_url('maintenance-action.php')) ?>"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="apply_update"><label class="admin-field full"><span>حزمة التحديث ZIP</span><input name="update" type="file" accept=".zip" required></label><label class="admin-field full"><span>كلمة مرورك الحالية</span><input name="password" type="password" required></label><label class="admin-field full"><span>اكتب UPDATE للتأكيد</span><input name="confirmation" pattern="UPDATE" required dir="ltr"></label><div class="admin-form-actions"><button class="admin-danger" type="submit" data-confirm="ستُنشأ نسخة ثم تُستبدل ملفات التطبيق الموجودة. هل تريد المتابعة؟">فحص وتطبيق التحديث</button></div></form></section>
  <section class="admin-card full"><div class="card-title"><div><span>UPDATE HISTORY</span><h2>سجل التحديثات</h2></div><em>تدقيق خادمي</em></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>الإصدار</th><th>الحالة</th><th>التفاصيل</th><th>التاريخ</th></tr></thead><tbody><?php if(!$updates): ?><tr><td colspan="4">لا توجد تحديثات مطبقة بعد.</td></tr><?php endif; ?><?php foreach($updates as $update): ?><tr><td dir="ltr"><?= h($update['version']) ?></td><td><?= h($update['status']) ?></td><td dir="ltr"><?= h($update['details_json']) ?></td><td dir="ltr"><?= h($update['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
<?php render_admin_end(); ?>
