<?php
/** One-screen, one-time web installer. Delete /install after success. */
declare(strict_types=1);

$root = dirname(__DIR__);
$storage = $root . '/storage';
$lock = $storage . '/installed.lock';
$runtime = $storage . '/database.php';

if (is_file($lock)) {
    http_response_code(403);
    exit('التثبيت مكتمل ومغلق مسبقاً. احذف مجلد install من الاستضافة.');
}

if (!is_dir($storage) || !is_writable($storage)) {
    http_response_code(500);
    exit('مجلد storage غير قابل للكتابة. اجعل صلاحيته 755 ثم أعد المحاولة.');
}

ini_set('session.use_strict_mode', '1');
session_name('SCFINSTALL');
session_set_cookie_params(['httponly' => true, 'secure' => !empty($_SERVER['HTTPS']), 'samesite' => 'Strict']);
session_start();
if (empty($_SESSION['install_csrf'])) $_SESSION['install_csrf'] = bin2hex(random_bytes(32));

$done = false;
$err = '';
$values = ['db_host' => 'localhost', 'db_name' => '', 'db_user' => '', 'admin_user' => 'csradmin'];

if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST') {
    foreach (array_keys($values) as $key) $values[$key] = trim((string)($_POST[$key] ?? $values[$key]));
    $dbPass = (string)($_POST['db_pass'] ?? '');
    $adminPass = (string)($_POST['admin_pass'] ?? '');
    $csrf = (string)($_POST['_csrf'] ?? '');

    if (!hash_equals((string)$_SESSION['install_csrf'], $csrf)) {
        $err = 'انتهت الجلسة. حدّث الصفحة وحاول مجدداً.';
    } elseif (!preg_match('/^[A-Za-z0-9._:-]{1,190}$/', $values['db_host'])) {
        $err = 'عنوان خادم قاعدة البيانات غير صالح.';
    } elseif (!preg_match('/^[A-Za-z0-9_$-]{1,190}$/', $values['db_name']) || !preg_match('/^[A-Za-z0-9_$-]{1,190}$/', $values['db_user'])) {
        $err = 'اسم قاعدة البيانات أو مستخدمها غير صالح.';
    } elseif (!preg_match('/^[A-Za-z0-9_.-]{4,40}$/', $values['admin_user'])) {
        $err = 'اسم الأدمن يجب أن يكون 4–40 حرفاً لاتينياً أو رقماً، بلا فراغات.';
    } elseif (strlen($adminPass) < 10) {
        $err = 'كلمة مرور الأدمن يجب أن تكون 10 أحرف على الأقل.';
    } else {
        try {
            $test = new PDO(
                'mysql:host=' . $values['db_host'] . ';dbname=' . $values['db_name'] . ';charset=utf8mb4',
                $values['db_user'],
                $dbPass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_TIMEOUT => 8]
            );
            $test = null;

            $cfg = [
                'host' => $values['db_host'],
                'name' => $values['db_name'],
                'user' => $values['db_user'],
                'pass' => $dbPass,
                'secret' => bin2hex(random_bytes(32)),
            ];
            $php = "<?php\n// Generated by the one-time installer. Direct web access is denied by storage/.htaccess.\nreturn " . var_export($cfg, true) . ";\n";
            $tmp = $runtime . '.tmp-' . bin2hex(random_bytes(5));
            if (file_put_contents($tmp, $php, LOCK_EX) === false || !rename($tmp, $runtime)) {
                @unlink($tmp);
                throw new RuntimeException('config-write');
            }
            @chmod($runtime, 0640);

            require_once __DIR__ . '/installer.php';
            installer_run($values['admin_user'], $adminPass);
            session_regenerate_id(true);
            unset($_SESSION['install_csrf']);
            $done = true;
        } catch (Throwable $e) {
            if (!is_file($lock)) @unlink($runtime);
            error_log('SCF installer: ' . $e->getMessage());
            $err = 'تعذر التثبيت. تحقق من بيانات قاعدة البيانات وأنها فارغة ومستخدمها يملك جميع الصلاحيات.';
        }
    }
}
?>
<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>تثبيت منتدى المسؤولية الاجتماعية واستدامة الأعمال العراقي</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Tahoma,Arial,sans-serif;background:linear-gradient(145deg,#0e1130,#24275f);color:#17203b;min-height:100vh;padding:28px;display:grid;place-items:center}.card{background:#fff;width:min(680px,100%);border-radius:20px;padding:28px;box-shadow:0 24px 70px #080a1f99}h1{margin:0;color:#24275f;font-size:24px}.sub{color:#66718a;margin:7px 0 22px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.wide{grid-column:1/-1}label{display:block;font-size:13px;font-weight:700;margin-bottom:5px}input{width:100%;border:1px solid #dce3ef;border-radius:10px;padding:12px;font-size:15px;outline:none}input:focus{border-color:#28a3db;box-shadow:0 0 0 3px #28a3db22}.section{grid-column:1/-1;font-weight:800;color:#196598;border-bottom:1px solid #e8edf5;padding:7px 0 5px;margin-top:5px}.btn{width:100%;border:0;border-radius:11px;padding:14px;background:linear-gradient(120deg,#2fb3ef,#1d7fc0);color:#fff;font-size:16px;font-weight:800;cursor:pointer}.msg{border-radius:11px;padding:13px;margin-bottom:16px;font-size:14px}.err{background:#fff1f3;color:#a51f38;border:1px solid #f3c5ce}.ok{background:#ecfff5;color:#11663f;border:1px solid #b8e9d0;line-height:2}.note{font-size:12px;color:#68728a;margin-top:13px}@media(max-width:600px){.grid{grid-template-columns:1fr}.wide,.section{grid-column:1}.card{padding:20px}body{padding:12px}}
</style></head><body><main class="card"><h1>تثبيت الموقع</h1><p class="sub">أدخل بيانات Hostinger ثم أنشئ حساب الأدمن. سيتم إعداد الموقع وقفل المثبّت تلقائياً.</p>
<?php if ($done): ?><div class="msg ok"><b>✓ تم التثبيت بنجاح.</b><br>لوحة التحكم: <a href="../<?= htmlspecialchars(ADMIN_DIR, ENT_QUOTES, 'UTF-8') ?>/">فتح لوحة التحكم</a><br><b>الآن احذف مجلد install بالكامل من مدير الملفات.</b></div>
<?php else: ?><?php if ($err): ?><div class="msg err"><?= htmlspecialchars($err, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<form method="post" autocomplete="off"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($_SESSION['install_csrf'], ENT_QUOTES, 'UTF-8') ?>"><div class="grid">
<div class="section">بيانات قاعدة البيانات</div>
<div><label>خادم قاعدة البيانات</label><input name="db_host" value="<?= htmlspecialchars($values['db_host'], ENT_QUOTES, 'UTF-8') ?>" required></div>
<div><label>اسم قاعدة البيانات</label><input name="db_name" value="<?= htmlspecialchars($values['db_name'], ENT_QUOTES, 'UTF-8') ?>" required></div>
<div><label>مستخدم قاعدة البيانات</label><input name="db_user" value="<?= htmlspecialchars($values['db_user'], ENT_QUOTES, 'UTF-8') ?>" required></div>
<div><label>كلمة مرور قاعدة البيانات</label><input type="password" name="db_pass" required autocomplete="new-password"></div>
<div class="section">حساب مدير الموقع</div>
<div><label>اسم دخول الأدمن</label><input name="admin_user" value="<?= htmlspecialchars($values['admin_user'], ENT_QUOTES, 'UTF-8') ?>" minlength="4" maxlength="40" required></div>
<div><label>كلمة مرور الأدمن (10 أحرف أو أكثر)</label><input type="password" name="admin_pass" minlength="10" required autocomplete="new-password"></div>
<div class="wide"><button class="btn" type="submit">اختبار الاتصال وتثبيت الموقع</button><p class="note">لا تُغلق الصفحة أثناء التثبيت. لا تُستخدم بيانات قاعدة البيانات إلا داخل موقعك.</p></div>
</div></form><?php endif; ?></main></body></html>
