<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require APP_ROOT . '/includes/layout.php';
$locale = current_locale();
$isAr = $locale === 'ar';
$metrics = content_data('metrics');
$timeline = content_data('timeline');
$departments = content_data('departments');
render_header($locale, $isAr ? 'من نحن' : 'About us');
?>
<main>
  <section class="inner-hero"><div class="section-shell"><p class="eyebrow"><span></span><?= $isAr ? 'قصتنا' : 'Our story' ?></p><h1><?= $isAr ? 'من مكتب علمي محلي إلى شريك وطني متكامل' : 'From scientific office to integrated national partner' ?></h1><p><?= $isAr ? 'منذ 1996 نطوّر القدرات التنظيمية والتشغيلية والتجارية التي تربط الشركات الدوائية العالمية بملايين المرضى في العراق.' : 'Since 1996, we have built the regulatory, operational and commercial capabilities that connect global pharmaceutical companies with millions of patients across Iraq.' ?></p></div></section>

  <section class="content-section"><div class="section-shell content-grid"><div class="prose"><p class="eyebrow"><span></span><?= $isAr ? 'من نحن' : 'Who we are' ?></p><h2><?= $isAr ? 'خبرة محلية عميقة وطموح يتجاوز التوزيع' : 'Deep local expertise with an ambition beyond distribution' ?></h2><p><?= $isAr ? 'مكتب بغداد الحياة العلمي إحدى أكثر الوكالات الدوائية خبرة وثقة في العراق. نمثل شركات مصنعة رائدة ونوفر وصولاً مستمراً إلى المنتجات عالية الجودة عبر فهم دقيق للأنظمة المحلية وشبكات توزيع ولوجستيات متقدمة.' : "Baghdad Al Hayat Scientific Office is one of Iraq's most experienced and trusted pharmaceutical agencies. We represent leading manufacturers and ensure consistent access to high-quality products through deep regulatory understanding and advanced distribution logistics." ?></p><p><?= $isAr ? 'يعمل أكثر من 525 متخصصاً من بغداد وأربيل والبصرة، بعد أن سجل الملف التعريفي السابق أكثر من 300 متخصص، لخدمة الطلب المتنامي على الرعاية الصحية.' : 'More than 525 professionals work from Baghdad, Erbil and Basra, growing from the 300+ professionals recorded in the earlier profile.' ?></p><div class="mission-vision"><div><span><?= $isAr ? 'المهمة' : 'Mission' ?></span><strong><?= $isAr ? 'تحسين جودة الحياة' : 'Improve quality of life' ?></strong><p><?= $isAr ? 'منتجات دوائية عالية الجودة وسياسات صحية محدثة ومعايير دولية.' : 'High-quality medicines, evolved health policy and international standards.' ?></p></div><div><span><?= $isAr ? 'الرؤية' : 'Vision' ?></span><strong><?= $isAr ? 'تطوير قطاع الصحة' : 'Develop healthcare' ?></strong><p><?= $isAr ? 'تعليم وتحول رقمي وحلول مبتكرة تتمحور حول المريض.' : 'Education, digital transformation and patient-centred innovation.' ?></p></div></div></div><div class="feature-image"><img src="<?= h(site_url('assets/images/headquarters.jpg')) ?>" alt="Baghdad Al Hayat headquarters"></div></div></section>

  <section class="metrics-band"><div class="section-shell metrics-grid"><div class="metrics-intro"><p><?= $isAr ? 'قدراتنا اليوم' : 'Our scale today' ?></p><span><?= $isAr ? 'بنية وطنية تُدار بمعايير عالمية' : 'National infrastructure managed to global standards' ?></span></div><?php foreach ($metrics as $metric): ?><div class="metric"><strong><?= h($metric['value']) ?></strong><span><?= h(localized($metric['label'], $locale)) ?></span></div><?php endforeach; ?></div></section>

  <section class="content-section"><div class="section-shell"><div class="section-heading compact-heading"><p class="eyebrow"><span></span><?= $isAr ? 'الهيكل التنظيمي' : 'Organisation structure' ?></p><h2><?= $isAr ? '13 إدارة متكاملة تحت قيادة المدير العام' : 'Thirteen integrated functions reporting to the General Manager' ?></h2></div><div class="pv-grid"><?php foreach ($departments as $index => $department): ?><article><span><?= str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) ?></span><p><?= h(localized($department, $locale)) ?></p></article><?php endforeach; ?></div></div></section>

  <section class="leadership-section"><div class="section-shell leadership-grid"><div class="leader-photo"><img src="<?= h(site_url('assets/images/ceo.png')) ?>" alt="Ali Mosawi, Founder and CEO"></div><blockquote><p class="eyebrow"><span></span><?= $isAr ? 'رسالة المؤسس والرئيس التنفيذي' : 'A message from our founder & CEO' ?></p><p>“<?= $isAr ? 'مهمتنا هي تسهيل الصلة بين قطاع الرعاية الصحية العراقي وأحدث ما توصل إليه الطب العالمي. يمنحنا الأثر الحقيقي لهذه الابتكارات دافعاً يومياً لإيصال العلاجات التي تجدد القوة والأمل.' : 'Our mission is to facilitate the connection between Iraqi healthcare and the latest advancements in global medicine. The tangible impact of these innovations is the daily motivation behind our work.' ?>”</p><footer><strong>Ali Mosawi</strong><span><?= $isAr ? 'المؤسس والرئيس التنفيذي' : 'Founder & CEO' ?></span></footer></blockquote><blockquote class="gm-quote"><p class="eyebrow"><span></span><?= $isAr ? 'رسالة المدير العام' : 'A message from our GM' ?></p><p>“<?= $isAr ? 'نجمع الخبرة الموثوقة مع التزام عميق بصحة المريض؛ من الامتثال التنظيمي إلى التوزيع الوطني نحرص على وصول العلاجات المنقذة للحياة بفاعلية ونزاهة.' : 'We combine trusted expertise with a deep commitment to patient wellbeing, ensuring life-saving treatments are accessible, effective and delivered with integrity.' ?>”</p><footer><strong>Dr. Zaid Haitham</strong><span><?= $isAr ? 'المدير العام' : 'General Manager' ?></span></footer></blockquote></div></section>

  <section class="content-section why-section"><div class="section-shell content-grid why-single"><div class="prose"><p class="eyebrow"><span></span><?= $isAr ? 'لماذا بغداد الحياة؟' : 'Why Baghdad Al Hayat?' ?></p><h2><?= $isAr ? 'استقرار وشفافية والتزام طويل الأمد' : 'Stability, transparency and long-term commitment' ?></h2><p><?= $isAr ? 'خبرة تتجاوز 30 عاماً وعمليات مستدامة وفريق ماهر وثقافة عمل عائلية، مع استمرار الاستثمار في القدرات حتى خلال فترات الأزمات.' : 'More than 30 years of experience, sustainable operations, a skilled team and a family-oriented culture, with continued investment even through periods of crisis.' ?></p><div class="detail-list"><div><?= $isAr ? 'استقرار مالي وشفافية مع تدقيق داخلي وخارجي' : 'Financial stability and transparency with internal and external audit' ?></div><div><?= $isAr ? 'امتثال لمتطلبات البنك المركزي العراقي' : 'Compliance with Central Bank of Iraq requirements' ?></div><div><?= $isAr ? 'أنظمة متقدمة للتدفق النقدي والكفاءة التشغيلية' : 'Advanced cash-flow and operating-efficiency systems' ?></div></div></div></div></section>

  <section class="content-section"><div class="section-shell"><div class="section-heading compact-heading"><p class="eyebrow"><span></span><?= $isAr ? 'محطاتنا' : 'Our milestones' ?></p><h2><?= $isAr ? 'أسس نمو بُنيت على مدى ثلاثة عقود' : 'Foundations built across three decades' ?></h2></div><div class="timeline light-timeline"><?php foreach ($timeline as $item): ?><article><strong><?= h($item['year']) ?></strong><div><h3><?= h(localized($item['title'], $locale)) ?></h3><p><?= h(localized($item['text'], $locale)) ?></p></div></article><?php endforeach; ?></div></div></section>

  <section class="content-section"><div class="section-shell content-grid"><div class="feature-image team-image"><video src="<?= h(site_url('assets/vid/office.mp4')) ?>" autoplay muted loop playsinline preload="metadata" aria-label="<?= $isAr ? 'مكتب بغداد الحياة العلمي' : 'Baghdad Al Hayat Scientific Office' ?>"></video></div><div class="prose"><p class="eyebrow"><span></span><?= $isAr ? 'أبطال بغداد الحياة' : 'The champs of Baghdad Al Hayat' ?></p><h2><?= $isAr ? 'قوة ميدانية مدعومة بالتقنية' : 'A field force powered by technology' ?></h2><p><?= $isAr ? '90 ممثلاً ميدانياً و10 مشرفين يقودون التنفيذ التجاري مدعومين بالتكامل بين أنظمة CRM وERP والرؤية القائمة على البيانات.' : 'Ninety field representatives and ten supervisors drive market execution, supported by integrated CRM and ERP systems and data-driven insight.' ?></p><div class="detail-list"><div><?= $isAr ? 'إدارة المخزون والطلبات والمرتجعات والتحصيل إلكترونياً' : 'Electronic stock, order, returns and collection management' ?></div><div><?= $isAr ? 'زيارات ميدانية ومتابعة مستمرة' : 'Field engagement and continuous customer follow-up' ?></div><div><?= $isAr ? 'معلومات سوق وقرارات مدعومة بالبيانات' : 'Market intelligence and data-supported decisions' ?></div></div></div></div></section>
</main>
<script nonce="<?= h(csp_nonce()) ?>">(()=>{const ids=['story','who','scale','organisation','leadership','why','milestones','team'];document.querySelectorAll('main>section').forEach((section,index)=>section.id=ids[index]||section.id);if(location.hash)requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView());})();</script>
<?php render_footer($locale); ?>
