<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require APP_ROOT . '/includes/layout.php';
$locale = current_locale(); $isAr = $locale === 'ar';
$partners = content_data('partners'); $commitments = content_data('commitments');
render_header($locale, $isAr ? 'الشركاء' : 'Global partners');
?>
<main>
  <section class="inner-hero"><div class="section-shell"><p class="eyebrow"><span></span><?= $isAr ? 'شراكات عالمية' : 'Global partnerships' ?></p><h1><?= $isAr ? 'نمثل الابتكار العالمي باستثمار محلي مخصص' : 'Global innovation, backed by dedicated local investment' ?></h1><p><?= $isAr ? 'نبني لكل شريك بنية تنظيمية وتجارية وتشغيلية طويلة الأمد مصممة خصيصاً لديناميكيات السوق العراقي.' : "For every partner, we build a long-term regulatory, commercial and operational platform designed specifically for Iraq's market dynamics." ?></p></div></section>
  <section class="content-section"><div class="section-shell"><div class="partner-list-large"><?php foreach ($partners as $index => $partner): ?><article><span><?= str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) ?></span><div class="partner-large-logo"><?php if ($partner['logo']): ?><img src="<?= h(site_url($partner['logo'])) ?>" width="210" height="90" alt="<?= h($partner['name']) ?> logo"><?php else: ?><strong><?= h($partner['name']) ?></strong><?php endif; ?></div><div><strong><?= h($partner['name']) ?></strong><small><?= $isAr ? 'بداية الشراكة' : 'Partnership established' ?> <?= h($partner['since']) ?></small></div></article><?php endforeach; ?></div></div></section>
  <section class="partners-promise"><div class="section-shell"><div class="section-heading compact-heading"><p class="eyebrow"><span></span><?= $isAr ? 'التزامنا' : 'Our promise' ?></p><h2><?= $isAr ? 'ما الذي يحصل عليه شريك بغداد الحياة؟' : 'What a Baghdad Al Hayat partner can expect' ?></h2></div><div class="commitment-grid"><?php foreach ($commitments as $item): ?><article><span><?= h($item['number']) ?></span><h3><?= h(localized($item['title'], $locale)) ?></h3><p><?= h(localized($item['body'], $locale)) ?></p></article><?php endforeach; ?></div></div></section>
  <section class="content-section"><div class="section-shell content-grid"><div class="feature-image partnership-photo"><img src="<?= h(site_url('assets/images/partner-meeting.jpg')) ?>" alt="Partnership meeting at Baghdad Al Hayat"></div><div class="prose"><p class="eyebrow"><span></span><?= $isAr ? 'دخول السوق' : 'Market entry' ?></p><h2><?= $isAr ? 'مسار واحد من الاستراتيجية إلى التنفيذ' : 'One path from strategy to execution' ?></h2><p><?= $isAr ? 'يعمل فريق الشراكات مع التسجيل والنفاذ للسوق والمبيعات وسلسلة الإمداد والجودة واليقظة الدوائية كوحدة واحدة لتقليل التعقيد وتحويل الخطة إلى حضور مستدام.' : 'Our partnerships team works as one unit with regulatory, market access, sales, supply chain, quality and pharmacovigilance functions to turn strategy into sustainable presence.' ?></p><div class="detail-list"><div><?= $isAr ? 'تحليل السوق والمسار التنظيمي' : 'Market and regulatory pathway assessment' ?></div><div><?= $isAr ? 'فريق ومنصة تجارية مخصصة' : 'Dedicated team and commercial platform' ?></div><div><?= $isAr ? 'تقارير أداء وحوكمة وامتثال مستمرة' : 'Ongoing performance, governance and compliance reporting' ?></div></div></div></div></section>
</main>
<?php render_footer($locale); ?>
