<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require APP_ROOT . '/includes/layout.php';
$locale = current_locale(); $isAr = $locale === 'ar';
$systems = content_data('quality_systems'); $facilities = content_data('facilities');
render_header($locale, $isAr ? 'الجودة والامتثال' : 'Quality & compliance');
?>
<main>
  <section class="inner-hero"><div class="section-shell"><p class="eyebrow"><span></span><?= $isAr ? 'الجودة والامتثال' : 'Quality & compliance' ?></p><h1><?= $isAr ? 'سلامة الدواء تبدأ قبل وصوله إلى المريض بوقت طويل' : 'Medicine safety starts long before it reaches the patient' ?></h1><p><?= $isAr ? 'أنظمة جودة وحوكمة وسلسلة تبريد ويقظة دوائية تحمي سلامة المنتج وبيانات الشركاء واستمرارية الأعمال.' : 'Quality systems, governance, cold-chain control and pharmacovigilance protect product integrity, partner data and business continuity.' ?></p></div></section>
  <section class="content-section"><div class="section-shell content-grid"><div class="prose"><p class="eyebrow"><span></span><?= $isAr ? 'ضمان الجودة' : 'Quality assurance' ?></p><h2><?= $isAr ? 'نظام متكامل، لا قائمة فحص' : 'An integrated system, not a checklist' ?></h2><p><?= $isAr ? 'نتبع ممارسات التخزين والتوزيع الجيد GSDP ونطبق رقابة صارمة مع التدقيق الداخلي والخارجي والتدريب المستمر وإدارة المخاطر.' : 'We follow GSDP-compliant practices and rigorous controls, including internal and external audits, continuous training and risk management.' ?></p><div class="detail-list"><div><?= $isAr ? 'مرجع الشهادة: 103/25' : 'Certificate reference: 103/25' ?></div><div><?= $isAr ? 'تاريخ الإصدار: 25/06/2025' : 'Issue date: 25 June 2025' ?></div><div><?= $isAr ? 'صالحة حتى سبتمبر 2026' : 'Valid until September 2026' ?></div></div><div class="quality-systems expanded"><?php foreach ($systems as $system): ?><div><strong><?= h($system['code']) ?></strong><span><?= h(localized($system['title'], $locale)) ?></span></div><?php endforeach; ?></div></div><div class="certificate-wrap"><img src="<?= h(site_url('assets/images/gsdp-certificate.jpg')) ?>" alt="GSDP certificate"></div></div></section>
  <section class="quality-highlight"><div class="section-shell highlight-grid"><div><strong>99.7%</strong><span><?= $isAr ? 'التزام بمتطلبات درجات الحرارة' : 'temperature compliance' ?></span></div><div><strong>46+</strong><span><?= $isAr ? 'ناقلاً مبرداً مزوداً بنظام GPS' : 'GPS-enabled cold-chain couriers' ?></span></div><div><strong>6</strong><span><?= $isAr ? 'مراكز توزيع تغطي العراق' : 'distribution centres across Iraq' ?></span></div></div></section>
  <section class="content-section"><div class="section-shell"><div class="section-heading compact-heading"><p class="eyebrow"><span></span><?= $isAr ? 'المرافق والتوسع' : 'Facilities & expansion' ?></p><h2><?= $isAr ? 'تفاصيل البنية التشغيلية في جميع المواقع' : 'The complete operating footprint across Iraq' ?></h2></div><div class="pv-grid"><?php foreach ($facilities as $index => $facility): ?><article><span><?= str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) ?></span><p><strong><?= h(localized($facility['city'], $locale)) ?></strong><br><?= h(localized($facility['detail'], $locale)) ?></p></article><?php endforeach; ?></div></div></section>
  <section class="pv-section"><div class="section-shell"><div class="section-heading compact-heading"><p class="eyebrow"><span></span><?= $isAr ? 'نظام اليقظة الدوائية' : 'Pharmacovigilance system' ?></p><h2><?= $isAr ? 'سلامة مستمرة طوال دورة حياة المنتج' : 'Continuous safety across the product lifecycle' ?></h2></div><div class="pv-grid"><article><span>01</span><p><?= $isAr ? 'سلامة المريض: اكتشاف وتقييم ومنع الآثار العكسية' : 'Patient safety: detect, assess and prevent adverse effects' ?></p></article><article><span>02</span><p><?= $isAr ? 'الامتثال لمعايير وزارة الصحة وFDA وEMA' : 'Compliance with MOH, FDA and EMA standards' ?></p></article><article><span>03</span><p><?= $isAr ? 'تكامل ضمان الجودة والتوثيق والإجراءات' : 'QA integration, documentation and SOP adherence' ?></p></article><article><span>04</span><p><?= $isAr ? 'المراقبة المستمرة واكتشاف الإشارات' : 'Continuous monitoring and signal detection' ?></p></article></div><div class="sop-grid"><div><strong><?= $isAr ? 'الإبلاغ عن الأحداث العكسية' : 'Adverse event reporting' ?></strong><span><?= $isAr ? 'جمع معلومات السلامة بدقة وفي الوقت المناسب' : 'Timely and accurate safety reporting' ?></span></div><div><strong><?= $isAr ? 'اكتشاف الإشارات' : 'Signal detection' ?></strong><span><?= $isAr ? 'تحديد المخاوف الجديدة استباقياً' : 'Proactive identification of new concerns' ?></span></div><div><strong>PSURs</strong><span><?= $isAr ? 'مراجعات دورية تُرفع للجهات المختصة' : 'Periodic reviews submitted to authorities' ?></span></div></div></div></section>
</main>
<?php render_footer($locale); ?>
